# Rutas
path:
  local:
    #main: "/Volumes/Resources/Development/SmartBots/Santa_Elena-Envio_Full_Set_a_Recibido"
    main: "D:/Dev/Santa_Elena-Envio_Full_Set_a_Recibido"
    source: "${path.local.main}/src"
    config: "${path.local.source}/configuracion"
    modules: "${path.local.source}/modules"
    models: "${path.local.source}/models"
    templates: "${path.local.source}/templates"
    logs: "${path.local.main}/logs"
  shared:
    #main: "/Volumes/Resources/Development/SmartBots/Santa_Elena-Envio_Full_Set_a_Recibido/test"
    #main: "D:/Dev/Santa_Elena-Envio_Full_Set_a_Recibido/test"
    main: "G:/Mi unidad/Bot RPA/COMEX/Envio de archivos a recibidor"
    config: "${path.shared.main}/Configuracion/Plantilla_de_Configuracion.xlsx"
    in_progress: "${path.shared.main}/En Proceso"
    done: "${path.shared.main}/Finalizados"

# Correo
mail:
  config:
    smtp:
      user: "jua.cuadra.v@gmail.com"
      password: "aelr kzut fcna ebnn"
      server: "smtp.gmail.com"
      port: 587
    api:
      scopes: ['https://www.googleapis.com/auth/gmail.send']
      credentials: "${path.local.config}/credentials.json"
      token: "${path.local.config}/token.json"
  template:
    report: "${path.local.templates}/Envio_Informe.html"
    receiver: "${path.local.templates}/Envio_Recibidor.html"
    empty: "${path.local.templates}/Envio_Vacio.html"
  sender:
    report:
      to: ""
      cc: ""
      cco: "h.buddenberg@gmail.com"